name: "install"
on:
  push
jobs:
  install_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: "install job"

        run: |
         find ./ -type f -name "add-post.component.html"

        working-directory: /





